### ISSUE TITLE
getGeneName returns outdated symbol instead of TRAPPC11

### ISSUE THREAD

**Issue by jxchong** [mutalyzer/mutalyzer#385]
It seems like getGeneName can retrieve outdated gene symbols. For example:

`https://www.mutalyzer.nl/json/getGeneName?build=hg19&accno=NM_021942.5` returns `C4orf41`

`https://www.mutalyzer.nl/json/runMutalyzer?variant=NM_021942.5:c.851A%3EC` returns 
`"transcriptDescriptions": ["NM_021942.5(TRAPPC11_v001):c.2938G>A"]`

This gene has been named `TRAPPC11` for quite a while (since at least before 2012)

**Comment by martijnvermaat** [comment]
Hi @jxchong thanks for reporting this!

You are correct. Actually, the Mutalyzer database has `C4orf41` for `NM_021942.4` and `TRAPPC11` for `NM_021942.5`. This already points me to a problem, and that is that older transcript versions will never be updated (nor will any entry on hg19 actually), since the NCBI mapview files we use for this are no longer being updated for hg19.

However, the issue here is a different one, since as I said our database actually has the newer gene symbol for transcript version 5 which you queried. From a quick glance at the code it looks like the transcript version is ignored by this webservice call. This shouldn't be hard to fix, I might have a look tomorrow.

**Comment by martijnvermaat** [comment]
Hi @jxchong, the fix is now available:

https://www.mutalyzer.nl/json/getGeneName?build=hg19&accno=NM_021942.5

**Comment by jxchong** [comment]
awesome thanks for the quick response!
