### ISSUE TITLE
Could not retrieve reference.

### ISSUE THREAD

**Issue by jfjlaros** [mutalyzer/mutalyzer#455]
The reference file for NM_001145306 (note the missing version number) could not be retrieved, after trying NM_001145306.1 (with version number) the file without version number works as well.

It seems that autocompletion of version numbers does not work as before, it now seems to rely on an internal state (perhaps a database) instead of retrieval via the NCBI.

**Comment by mihailefter** [comment]
Something is strange, since I was not able to reproduce the issue. I used some references that were not cached, e.g., `NM_001145321`, without the version number, and they were successfully retrieved (with the following warning: _No version number is given, using NM_001145321.1. Please use this number to reduce downloading overhead._).

Could you please provide more information on your specific example? From the DB, I see that `NM_001145306` was cached on 2012-02-04.

**Comment by mihailefter** [comment]
After checking the log it seems like there was some connection error with the Entrez nuccore database.
