### ISSUE TITLE
Wrong interpretation of conversions.

### ISSUE THREAD

**Issue by jfjlaros** [mutalyzer/mutalyzer#53]
The following [conversion](https://v3.mutalyzer.nl/namechecker/LRG_199:g.100_200con300_400) gets corrected to `LRG_199:g.=`, which does not look right to me.

**Comment by ifokkema** [comment]
On a related note; since conversions are now told to be described as deletion-insertions, I tried sending the same variant as a deletion-insertion. For a genomic reference sequence, this [generates a valid description](https://v3.mutalyzer.nl/namechecker/LRG_199:g.100_200delins300_400). However, for a transcript reference sequence, this generates a [description that can never be correct](https://v3.mutalyzer.nl/namechecker/LRG_199t1:c.100_200delins300_400). Mutalyzer 2 refuses to do this for a transcript sequence. I assume this is because of introns being present. I do think, however, that such a description should be valid input since it's possible that indeed entire exons were copied, and the introns between them were also spliced out, resulting in a "clean" insertion on `c.` level... :thinking:

**Comment by jfjlaros** [comment]
That sure is a long description. I opened an other bug report (#54) for this.

I am also not sure how to interpret something like `c.1_2ins100_200` by the way. For now we assume that all these ranges are given in the `g.` coordinate system.

**Comment by jfjlaros** [comment]
It seems there is an off by one error: [LRG_199:g.100_200con300_400](https://v3.mutalyzer.nl/normalizer/LRG_199:g.100_200con300_400).

**Comment by mihailefter** [comment]
It's not: `LRG_199:g.200 == LRG_199:g.400 == 'T'`.
