### ISSUE TITLE
Have Name Checker convert "chr1" to proper NCBI Gene ID

### ISSUE THREAD

**Issue by cathtyner** [mutalyzer/mutalyzer#55]
**Suggestion/Improvement**
When entering something like, "chr1:g.169519049C>T" into Name Checker, 
It would be helpful for MUT to return, or go ahead and convert, "chr1" to NC_000001.10

**Comment by jfjlaros** [comment]
The problem is that "chr1" is ambiguous, it could refer to chromosome 1 of any patch of any build of any species. E.g., human build GRCh38.p13 or mouse build GRCm39.p0, etc. So perhaps something along the lines of GRCh38.p13:chr1:169519049C>T` could work.

You might want to discuss this with the [HGVS nomenclature committee](https://varnomen.hgvs.org/) instead.
