### ISSUE TITLE
Short descriptions of variants are not interpreted correctly

### ISSUE THREAD

**Issue by flohwie** [mutalyzer/mutalyzer#77]
Using a GenBank coding DNA reference sequence only (without genomic reference sequence) 
**sometimes** produces an error message stating that 
another nucleotide was found in the reference sequence instead. 

_Example:_
**NC_000022.10(NM_001372044.2):c.4612G>A** 
outputs correct rersults, while
**NM_001372044.2:c.4612G>A** 
alone produces the follwing error:
"Description could not be interpreted."
"G not found in the reference sequence, found C instead."

This works, however, in most cases for other reference sequences, such as _e.g._:
**NM_002522.4:c.1109A>G**
which produces correct output for Chromosomal Descriptions, 
RNA Prediction, Protein Prediction etc. ...

**Comment by mihailefter** [comment]
The  noticed behavior is because the chromosomal transcript, i.e., `NC_000022.10(NM_001372044.2)`, sequence is different than the `NM_001372044.2` sequence (see the [mapper] output for more details). Hence, `c.4612` does not refer to the same nucleotide.

For `NM_002522.4`, the chromosomal transcript and the RefSeq transcript sequences are the same.

[mapper]: https://mutalyzer.nl/mapper?description=NM_001372044.2%3Ac.%3D&reference_id=NC_000022.11&selector_id=NM_001372044.2&slice_to=transcript
